# Generated by Django 5.0.12 on 2025-02-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('productivity', models.FloatField()),
                ('quality', models.FloatField()),
                ('timeliness', models.FloatField()),
                ('total_score', models.FloatField()),
            ],
        ),
    ]
